let defBG = "rgba(238, 217, 25, 0)";

function nav(navi) {
    navi.style.backgroundColor = "black";
}

function nav2(navi) {
    navi.style.backgroundColor = defBG;
}


function hide() {
    let display = document.getElementById("tbody1");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide1() {
    let display = document.getElementById("tbody2");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide2() {
    let display = document.getElementById("tbody3");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide3() {
    let display = document.getElementById("tbody4");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide4() {
    let display = document.getElementById("tbody5");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide5() {
    let display = document.getElementById("tbody6");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide6() {
    let display = document.getElementById("tbody7");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide7() {
    let display = document.getElementById("tbody8");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide8() {
    let display = document.getElementById("tbody9");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}

function hide9() {
    let display = document.getElementById("tbody10");
    if (display.style.visibility === "collapse") {
        display.style.visibility = "visible";
    }
    else {
        display.style.visibility = "collapse";
    }
}